@echo off

cd /d %~dp0

set PATH=%PATH%;%~dp0redist\nsis

cmake -E remove_directory build
cmake -E make_directory  build

if DEFINED APPLICATION_NAME_TR (
set APPLICATION_NAME_TR_DEF=-DCOMPILE_APP_NAME_TR=%APPLICATION_NAME_TR%
) else (
set APPLICATION_NAME_TR_DEF=
)

if DEFINED APPLICATION_NAME (
set APPLICATION_NAME_DEF=-DCOMPILE_APP_NAME=%APPLICATION_NAME%
) else (
set APPLICATION_NAME_DEF=
)

if DEFINED ORGANIZATION_NAME_TR (
set ORGANIZATION_NAME_TR_DEF=-DCOMPILE_ORG_NAME_TR=%ORGANIZATION_NAME_TR%
) else (
set ORGANIZATION_NAME_TR_DEF=
)

if DEFINED ORGANIZATION_NAME (
set ORGANIZATION_NAME_DEF=-DORGANIZATION_NAME=%ORGANIZATION_NAME%
) else (
set ORGANIZATION_NAME_DEF=
)

cmake -H./ -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Release -DMAKE_TESTS=OFF -DPROJECT_NAME_LOW=landserver -DBOARD=OFF -DLAND=ON -DLANDSERVER_ONLY=ON -DLANDCLIENT_ONLY=OFF -DLANDFFMPEG=OFF -DLANDSERVER_H264TOJPEG=ON -DLANDSERVER_CLIENTEAPI=OFF -DLANDSERVER_INTERNAL=OFF -DINSTALL_RUNTIME_LIBS=ON -DINSTALL_RUNTIME_PATH=ON -DCREATE_BUNDLE=ON -DCMAKE_INSTALL_PREFIX=./out -DPROJECTVERSION=%PRODUCT_VERSION_REL% || exit 1
cmake --build build --target all || exit 1
cmake --build build --target install || exit 1
cmake --build build --target package || exit 1

exit /B 0
