@echo off

pushd
cd /d %~dp0

set PATH=%PATH%;%~dp0redist\nsis

cmake -E remove_directory build
cmake -E make_directory  build

cd build

if DEFINED APPLICATION_NAME_TR (
set APPLICATION_NAME_TR_DEF=-DCOMPILE_APP_NAME_TR=%APPLICATION_NAME_TR%
) else (
set APPLICATION_NAME_TR_DEF=
)

if DEFINED APPLICATION_NAME (
set APPLICATION_NAME_DEF=-DCOMPILE_APP_NAME=%APPLICATION_NAME%
) else (
set APPLICATION_NAME_DEF=
)

if DEFINED ORGANIZATION_NAME_TR (
set ORGANIZATION_NAME_TR_DEF=-DCOMPILE_ORG_NAME_TR=%ORGANIZATION_NAME_TR%
) else (
set ORGANIZATION_NAME_TR_DEF=
)

if DEFINED ORGANIZATION_NAME (
set ORGANIZATION_NAME_DEF=-DORGANIZATION_NAME=%ORGANIZATION_NAME%
) else (
set ORGANIZATION_NAME_DEF=
)

cmake -E remove CMakeCache.txt

cmake -G Ninja ../ -DNO_BACKTRACE=ON -DCMAKE_BUILD_TYPE=Release -DMAKE_TESTS=OFF -DBOARD=OFF -DLANDCLIENT_ONLY=OFF -DLANDSERVER_ONLY=OFF -DLANDSERVER_INTERNAL=ON -DUSE_MAP=OFF -DNEED_GEO_LIB=OFF -DLANDFFMPEG=OFF -DINSTALL_RUNTIME_LIBS=ON -DCREATE_BUNDLE=ON -DVISCA_CLIENT=ON -DBASE_TCP_CLIENT=ON -DMAVLINKGCS_CLIENT=ON -DNEED_GEO_LIB=OFF -DCMAKE_INSTALL_PREFIX=./out/viscacl -DPROJECTVERSION=%PRODUCT_VERSION_REL% %APPLICATION_NAME_TR_DEF% %ORGANIZATION_NAME_TR_DEF% %APPLICATION_NAME_DEF% %ORGANIZATION_NAME_DEF% || exit 1

ninja all || exit 1

ninja install || exit 1
ninja package || exit 1

popd
exit /B 0
