#!/bin/sh

#export
cd `dirname $0`
source ./mkrel-board.sh -cmake_arg "-DUSE_QT5=ON -DINSTALL_PROFILES=ON -DINSTALL_PROFILE_DEF_SYMLINK=ON -DINSTALL_PROFILE_DEF_SYMLINK_NAME=default -DBOARD_ALL_IN_ONE=ON -DREGULAR_SYSTEM=ON -DCPACK_GENERATOR_ADD=DEB" "${@}"
