@echo off

pushd
:: cd /d %~dp0

::set PATH=%PATH%;%~dp0redist\nsis
set SRC=%~dp0
set BUILD=Y:\build
set

:: pause

cmake -E remove_directory %BUILD%
cmake -E make_directory %BUILD%

cd /d %BUILD%
set ONLY_REGULAR_PROFILE=ON

if DEFINED APPLICATION_NAME_TR (
set APPLICATION_NAME_TR_DEF=-DCOMPILE_APP_NAME_TR=%APPLICATION_NAME_TR%
) else (
set APPLICATION_NAME_TR_DEF=
)

if DEFINED APPLICATION_NAME (
set APPLICATION_NAME_DEF=-DCOMPILE_APP_NAME=%APPLICATION_NAME%
) else (
set APPLICATION_NAME_DEF=
)

if DEFINED ORGANIZATION_NAME_TR (
set ORGANIZATION_NAME_TR_DEF=-DCOMPILE_ORG_NAME_TR=%ORGANIZATION_NAME_TR%
) else (
set ORGANIZATION_NAME_TR_DEF=
)

if DEFINED ORGANIZATION_NAME (
set ORGANIZATION_NAME_DEF=-DORGANIZATION_NAME=%ORGANIZATION_NAME%
) else (
set ORGANIZATION_NAME_DEF=
)

cmake -E remove CMakeCache.txt

cmake -G Ninja %SRC% -DCREATE_NSIS_INSTALLER=OFF -DNO_BACKTRACE=ON -DCMAKE_BUILD_TYPE=Release -DMAKE_TESTS=ON -DBOARD=OFF -DLANDCLIENT_ONLY=ON -DLANDSERVER_ONLY=ON -DLANDSERVER_INTERNAL=ON -DUSE_MAP=ON -DLANDFFMPEG=ON -DINSTALL_RUNTIME_LIBS=ON -DCREATE_BUNDLE=ON -D_SUPPORT_ThermoContour=ON -DCMAKE_INSTALL_PREFIX=./out/landclient_noserv -DPROJECTVERSION=%PRODUCT_VERSION_REL% %APPLICATION_NAME_TR_DEF% %ORGANIZATION_NAME_TR_DEF% %APPLICATION_NAME_DEF% %ORGANIZATION_NAME_DEF% || exit 1

ninja all

:: ctest -V || exit 1

ninja install
ninja package

:: pause

:: echo %ONLY_REGULAR_PROFILE%
:: echo Build only regular profile

:: No CARGOCHANNEL configuration
:: cmake -G Ninja %SRC% -DNO_BACKTRACE=ON -DCMAKE_BUILD_TYPE=Release -DMAKE_TESTS=OFF -DBOARD=OFF -DLANDCLIENT_PROFILE_GST=OFF -DLANDCLIENT_PROFILE_WEDDING=OFF -DLANDCLIENT_PROFILE_AIR=OFF -DLANDCLIENT_PROFILE_CARGO_CHANNEL=OFF -DLANDCLIENT_PROFILE_MSS=OFF -DLANDCLIENT_PROFILE_ROSATOM=OFF -DLANDCLIENT_PROFILE_SWALLOW=OFF -DLANDCLIENT_PROFILE_REDUT=OFF -DLANDCLIENT_PROFILE_ANGOLA=OFF -DUSE_MAP=ON -DLANDCLIENT_ONLY=ON -DLANDSERVER_ONLY=ON -DLANDSERVER_INTERNAL=ON -DLANDFFMPEG=ON -DINSTALL_RUNTIME_LIBS=ON -DCREATE_BUNDLE=ON -DCMAKE_INSTALL_PREFIX=./out_nocargochannel/landclient_noserv_nocargochannel -DPROJECTVERSION=%PRODUCT_VERSION_REL% %APPLICATION_NAME_TR_DEF% %ORGANIZATION_NAME_TR_DEF% %APPLICATION_NAME_DEF% %ORGANIZATION_NAME_DEF%

:: ninja all
:: ninja install
:: ninja package

:: pause

:: popd
:: exit /B 0
