#!/bin/sh
cd `dirname $0`

#export

rm -rf  build
mkdir build
cd build

cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON=python -DUDEV_LIBRARY=/lib/x86_64-linux-gnu/libudev.so.0 -DMAKE_TESTS=ON -DLAND=ON -DLANDCLIENT_ONLY=ON -DLANDSERVER_ONLY=ON -DBOARD=OFF -DLANDFFMPEG=ON -DINSTALL_RUNTIME_LIBS=ON -DINSTALL_RUNTIME_PATH=ON -DCMAKE_BUILD_TYPE=Release -DPROJECTVERSION=$PRODUCT_VERSION_REL
make -j6 || exit 1
ctest -V -E SystemTest || exit 1

cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON=python -DUDEV_LIBRARY=/lib/x86_64-linux-gnu/libudev.so.0 -DMAKE_TESTS=OFF -DLAND=ON -DLANDCLIENT_ONLY=OFF -DLANDSERVER_ONLY=ON -DBOARD=OFF -DLANDFFMPEG=OFF -DINSTALL_RUNTIME_LIBS=ON -DINSTALL_RUNTIME_PATH=ON -DCMAKE_BUILD_TYPE=Release -DPROJECTVERSION=$PRODUCT_VERSION_REL
DESTDIR=out/server make install package -j6 || exit 1

cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON=python -DUDEV_LIBRARY=/lib/x86_64-linux-gnu/libudev.so.0 -DMAKE_TESTS=OFF  -DLAND=ON -DLANDCLIENT_ONLY=ON -DLANDSERVER_ONLY=OFF -DBOARD=OFF -DLANDFFMPEG=ON -DINSTALL_RUNTIME_LIBS=ON -DINSTALL_RUNTIME_PATH=ON -DCMAKE_BUILD_TYPE=Release -DPROJECTVERSION=$PRODUCT_VERSION_REL
DESTDIR=out/client make install package -j6 || exit 1

exit 0;
